// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	dataservice "github.com/buidl-labs/Demux/dataservice"
	mock "github.com/stretchr/testify/mock"
)

// DatabaseHelper is an autogenerated mock type for the DatabaseHelper type
type DatabaseHelper struct {
	mock.Mock
}

// Client provides a mock function with given fields:
func (_m *DatabaseHelper) Client() dataservice.ClientHelper {
	ret := _m.Called()

	var r0 dataservice.ClientHelper
	if rf, ok := ret.Get(0).(func() dataservice.ClientHelper); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dataservice.ClientHelper)
		}
	}

	return r0
}

// Collection provides a mock function with given fields: name
func (_m *DatabaseHelper) Collection(name string) dataservice.CollectionHelper {
	ret := _m.Called(name)

	var r0 dataservice.CollectionHelper
	if rf, ok := ret.Get(0).(func(string) dataservice.CollectionHelper); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dataservice.CollectionHelper)
		}
	}

	return r0
}
