// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	model "github.com/buidl-labs/Demux/model"
	mock "github.com/stretchr/testify/mock"
)

// MeanSizeRatioDatabase is an autogenerated mock type for the MeanSizeRatioDatabase type
type MeanSizeRatioDatabase struct {
	mock.Mock
}

// GetMeanSizeRatio provides a mock function with given fields:
func (_m *MeanSizeRatioDatabase) GetMeanSizeRatio() (model.MeanSizeRatio, error) {
	ret := _m.Called()

	var r0 model.MeanSizeRatio
	if rf, ok := ret.Get(0).(func() model.MeanSizeRatio); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.MeanSizeRatio)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertMeanSizeRatio provides a mock function with given fields: _a0
func (_m *MeanSizeRatioDatabase) InsertMeanSizeRatio(_a0 model.SizeRatio) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.SizeRatio) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateMeanSizeRatio provides a mock function with given fields: _a0, _a1, _a2
func (_m *MeanSizeRatioDatabase) UpdateMeanSizeRatio(_a0 float64, _a1 float64, _a2 uint64) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(float64, float64, uint64) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
