// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mocks

import (
	model "github.com/buidl-labs/Demux/model"
	mock "github.com/stretchr/testify/mock"
)

// SizeRatioDatabase is an autogenerated mock type for the SizeRatioDatabase type
type SizeRatioDatabase struct {
	mock.Mock
}

// InsertSizeRatio provides a mock function with given fields: _a0
func (_m *SizeRatioDatabase) InsertSizeRatio(_a0 model.SizeRatio) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.SizeRatio) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
