on: [push, pull_request]
name: Test
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.4, 1.14.2]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download dependencies
        run: go mod download
      - name: Build
        run: go build ./cmd/main.go
